version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      CONTENTFUL_SPACE_ID: <your_space_id>
      CONTENTFUL_ACCESS_TOKEN: <your_access_token>
  clockwork:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec clockwork lib/clock.rb"
