default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: contentful_everywhere_local_db
test:
  <<: *default
  database: myapp_test
